Check for skipped file before processing content
This is what happens when you don’t write tests :-(

The error was:

Skipping archive/afss/Gemfile.lock
bundler: failed to load command: bin/organization_gem_dependencies (bin/organization_gem_dependencies)
NoMethodError: undefined method `match' for nil:NilClass
  /Users/magne/.rvm/rubies/ruby-2.6.3/lib/ruby/site_ruby/2.6.0/bundler/lockfile_parser.rb:69:in `initialize'
  /Users/magne/src/organization_gem_dependencies/lib/organization_gem_dependencies/cli.rb:39:in `new'
  /Users/magne/src/organization_gem_dependencies/lib/organization_gem_dependencies/cli.rb:39:in `block in run'
  /Users/magne/src/organization_gem_dependencies/lib/organization_gem_dependencies/cli.rb:122:in `block in remote_search'
  /Users/magne/src/organization_gem_dependencies/lib/organization_gem_dependencies/cli.rb:121:in `each'
  /Users/magne/src/organization_gem_dependencies/lib/organization_gem_dependencies/cli.rb:121:in `remote_search'
  /Users/magne/src/organization_gem_dependencies/lib/organization_gem_dependencies/cli.rb:38:in `run'
  bin/organization_gem_dependencies:5:in `<top (required)>'